### ISSUE TITLE
[建议]添加CDN下载方式

### ISSUE THREAD

**Issue by misaka10843** [gc-toolkit/gc-cli#3]
因为总所周知的原因，导致大陆时常无法正常连接GitHub或者速度缓慢

虽然在下载核心的文件的时候是可以走其他的构建链接

但是获取json配置文件/资源文件/插件时还是会走GitHub

所以就想问一下能否添加CDN下载方式，来加快资源下载速度？

**Comment by SwetyCore** [comment]
资源文件依然可以使用 -p 来加速下载
